version: 2

# Build with VitePress and publish generated static HTML.
build:
  os: ubuntu-22.04
  tools:
    nodejs: "20"
  jobs:
    install:
      - npm install
    build:
      html:
        - chmod +x utils/rtd-build.sh
        - ./utils/rtd-build.sh
