version: 2

# Build Container
build:
  os: ubuntu-22.04
  tools:
    nodejs: "20"
    python: "3.11"
  jobs:
    build:
      - npm ci
      - npx vitepress build docs/EN --outDir $READTHEDOCS_OUTPUT/html
